//
// Generated by Bluespec Compiler (build 00185f79)
//
// On Wed Apr  7 21:35:58 IST 2021
//
//
// Ports:
// Name                         I/O  size props
// the_answer                     O    32
// RDY_the_answer                 O     1 const
// the                            O    32
// RDY_the                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// the_answer_x                   I    32
// the_answer_y                   I    32
// the_answer_z                   I    32
// the_a                          I    32
// the_b                          I    32
// the_c                          I    32
//
// Combinational paths from inputs to outputs:
//   (the_answer_x, the_answer_y, the_answer_z) -> the_answer
//   (the_a, the_b, the_c) -> the
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkModuleDeepThought(CLK,
			   RST_N,

			   the_answer_x,
			   the_answer_y,
			   the_answer_z,
			   the_answer,
			   RDY_the_answer,

			   the_a,
			   the_b,
			   the_c,
			   the,
			   RDY_the);
  input  CLK;
  input  RST_N;

  // value method the_answer
  input  [31 : 0] the_answer_x;
  input  [31 : 0] the_answer_y;
  input  [31 : 0] the_answer_z;
  output [31 : 0] the_answer;
  output RDY_the_answer;

  // value method the
  input  [31 : 0] the_a;
  input  [31 : 0] the_b;
  input  [31 : 0] the_c;
  output [31 : 0] the;
  output RDY_the;

  // signals for module outputs
  wire [31 : 0] the, the_answer;
  wire RDY_the, RDY_the_answer;

  // value method the_answer
  assign the_answer = the_answer_x + the_answer_y + the_answer_z ;
  assign RDY_the_answer = 1'd1 ;

  // value method the
  assign the = the_a + the_b - the_c ;
  assign RDY_the = 1'd1 ;
endmodule  // mkModuleDeepThought

